[project]
name = 'Decentralized-Rare-Disease-Patient-Registry'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.patient-registration]
path = 'contracts/patient-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-registry]
path = 'contracts/patient-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
